# Generated by Django 4.1.5 on 2023-01-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='charity_abn',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
