# Generated by Django 4.1.5 on 2023-01-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(choices=[('climate change', 'CLIMATE CHANGE'), ('mental health', 'MENTAL HEALTH'), ('animal rights', 'ANIMAL RIGHTS')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='causes',
            field=models.ManyToManyField(to='projects.cause'),
        ),
    ]
