# Generated by Django 4.1.5 on 2023-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_cause_project_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='causes',
        ),
        migrations.AddField(
            model_name='project',
            name='cause',
            field=models.CharField(choices=[('climate change', 'CLIMATE CHANGE'), ('mental health', 'MENTAL HEALTH'), ('animal rights', 'ANIMAL RIGHTS')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
    ]
